### ISSUE TITLE
Non-structural input

### ISSUE THREAD

**Issue by pckroon** [marrink-lab/vermouth-martinize#16]
We want to allow non-structural input, such as an amino-acid sequence. Currently we're bound to atomistic gro and pdb.

**Comment by jbarnoud** [comment]
This requires to encode what edge needs to be added between residues.

Ping @fgrunewald

**Comment by fgrunewald** [comment]
My favorite idea is to use a parallel libraries of itps with dangling bonds, from that create a vermouth molecule. That's super easy and robust. Also quite fast. I've an implementation based on polyply, which should be adoptable and can support (pre-defined) branching. But we'd bypass the graph-matching, which is really not necessary for this particular problem and have a parallel library of itps and stuff.

**Comment by jbarnoud** [comment]
I think it is indeed doable with vermouth. How do you choose what anchor point goes with what branch, though?

**Comment by pckroon** [comment]
We should think about a fileformat for this for Vermouth as well. It'll be necessary for backmapping as well.

Step one in this is creating a disconnected `Molecule` of residues/blocks. This is easy: just keep calling `Molecule.merge_molecule`. The edges between residues are a little trickier.

My idea is that this becomes a separate processor. It'll take a disconnected molecule of residues (easy to make), and a graph with residues as nodes. Then, based on this and the data files it'll add edges to the disconnected molecule. 

Once this processor exists it should also be (used by/called after) the mapping processor, which currently adds edges between two nodes if there is an edge between two atoms that map to those nodes. We'll probably need both mechanisms: a) edges between residues that come from edges in a higher resolution graph and b) edges between residues that come from edges in a lower resolution graph and data files.

**Comment by fgrunewald** [comment]
@jbarnoud branching can be done by clever counting; or at least I like to think it's clever. But probably we're not gonna get around having some polymer specific rules somewhere. For now to construct a graph covering all the bond edges only requires the number of branching points and the atoms from which to branch as input and the number of atoms/beads per generation.

**Comment by fgrunewald** [comment]
@pckroon   In principle just calling Molecule.merge_molecule works. But the current file format for blocks becomes increasingly difficult to use; that is especially when you have many of the lower resolution edges that need to be added for no intuitive reasons. I will not implement atomistic polymers using this format, because that will require a ton of links and edges to be added. And the origin of the difficulty - as far as I can tell - is the graph matching: It looks a) for exact matches of everything that is in a block definition (that is cannot handle dangling bonds for instance) and b) requires edges to be added which are non-intuative; that is edges that are not bonds. If we can fix a and b we can use the graphing. Otherwise for amino-acids you probably will be fine but anything else quickly becomes quite difficult especially for 'layman'.

**Comment by fgrunewald** [comment]
@pckroon I stand corrected the graph matching is awesome, once you bypass the limitation that within one residue the atom names need to be unique, because they don't. Instead if you want to generate a highly branched itp you can simply define one generation as residue and the graph will link all the branches between generations. See picture enclosed for definition of residues. So basically we can generate everything from sequence by just being smart and having some sort of wrapper that deconstructs the sequence into a linear chain and corresponding branches. 
![hyperbranching](https://user-images.githubusercontent.com/32294573/46250733-07f1b700-c441-11e8-9509-73ff0602be06.png)

**Comment by pckroon** [comment]
@fgrunewald I'm not sure I understand all your concerns/issues. And I assume that when you say "graph matching" you mean applying links? In the code base there is a lot of "graph matching" going on, all slightly different.

Within a block the atomnames *must* be unique, for two reasons: 1) they're used as dictionary keys in some places in the code; and 2) Blocks also define bonded parameters, and in the file format they refer to atoms by name. That means that if your atomnames are not unique within a block you loose atoms, and you can no longer define your bonded parameters in a sane way.
In Links however, you can say that the atomname of a node must match *one of* these names, allowing more flexible matching. I'm a bit hazy on the exact fileformat syntax, but I'm sure @jbarnoud can fill you in there.

I don't see the advantage of using unintuitive residue numbers. My suggestion is the following: let's say that for a block you define 3 connection points. These connection points are ordered, and connections to neighbouring residues are made in order. In the picture above: `1:1` connects to 2, `1:2` connects to 3 and `1:3` connects to 4. The open problem now is deciding what connection point to use on the other side (`2:1`? or `2:2`?). My suggestion: step 1) in the algorithm is to find all outgoing connections to residues with a *higher* resid, for all residues. Step 2) for every residue, see which connections points are still unused, and use those to fulfil the incoming connections. In the example above, you'd get the following edges: `1:1-2:3`, `1:2-3:3`, `1:3-4:3`, `2:1-5:3`, `2:2-6:3` and `2:3-1:1`, etc.

**Comment by pckroon** [comment]
As an alternative, we could maybe also use the information in the Links for this. But that's going to be non-trivial.

**Comment by jbarnoud** [comment]
We could have named stubs defined in the blocks (stub in, and stub out). When building from sequence, the user can specify the stub combinations. If the names are normalized, we can use conventions for most cases and avoid extra user input.

In the case of a martini polypeptide, the "BB" bead would be both the stub in and the stub out. In the case of martini polystyrene, STYR would have a stub in on "B" and a stub out on "R1".

The name convention would allow automatic matching. By default, an edge can be added between a stub out and a stub in if they have the same name. Having the same stub names for all the amino acids allows to set the connectivity without specific user input. Because the stubs are named differently in STYR and in amino acids, the user would have to specifically allow the edge, avoiding weird matching. Same-wise, having the same stub name between STYR and PEG allows easy linear copolymers.

In the case of dendrimers, if the attach point are different for the different branches, then the automatic edge would work as described above. If the attachment is ambiguous, then the user would have to specify how to connect by telling what stub to connect with which one. Note that the dangling interactions does not solve the ambiguous attach point case.

Practically, the stub system is close to what @Tsjerk had in mind for grappa, I think. It does not require any change in the file format.

**Comment by fgrunewald** [comment]
I see all your points, I'm just telling that you don't need to apply any changes but you are welcome to do so of course. I'll send you the test case by mail and we can discuss in person on Monday.

**Comment by fgrunewald** [comment]
I think we decided for the time being we only allow structural input. Also for almost all other cases polyply should suffice.
