### ISSUE TITLE
`-merge` does not play well with elastic networks

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#221]
Using the `-merge` option with the elastic network or a go model can cause issues. There are two behaviours that can be desirable:

* the merge is done *before* the elastic network leading to bonds between the chains
* the merge is done *after* the elastic network leading to *no* bonds between the chains

Disulfide bonds add a layer to the issue: by bridging chains into a single a `Molecule` they always cause elastic bonds between the chains.

Possible solutions are:
* use chains to filter the elastic network
* split molecules around disulfide bridges when building the elastic networks

Test cases:
* simpler case: single chain (should keep working)
* A A merge before -> create bonds between the chains
* A A merge after -> do not create bonds between the chains
* A B merge before -> create bonds between the chains
* A B merge after -> do not create bonds
* A-s-s-A merge before -> create bonds
* A-s-s-A merge after -> do not create bonds (carreful with the bridges, test with more than 1 bridge)

How does it behave with `-sep`?

**Comment by pckroon** [comment]
I think what's most important in deciding which behaviour is desirable is what users /expect/ to happen. That means this should be cross-referenced and checked with the people actually using the software.

As I see it now:
- merged chains should result in elastic bonds between the chains.
- elastic bonds should be confined to Molecules.
- elastic bonds should be confined to chains.
So:
A A -> no cross bonds
A B -> no cross bonds
A-ss-B -> no cross bonds
A-ss-A -> yes cross bonds

My preference would be to use chains to filter the elastic bonds, rather than creative splitting.

I think `-sep` is mostly unrelated since it doesn't affect the topologies themselves, only how many files are written.

**Comment by jbarnoud** [comment]
I am going toward the filtering. I am making the filtering general enough that it could be done on whatever rule you want (by passing a callback) and I'll add a "connect chains" flag for the CLI.

**Comment by Tsjerk** [comment]
-sep is (was) only intended to write separate topology files even if the topologies are equal, e.g., to make it easy to make small modifications to one, but not the others.

The point about -merge was to create one _molecule_, i.e., one _moleculetype_, so one itp file. This was necessary for making links, like SS bonds (and for that reason, links and ssbonds automatically caused merging if they crossed chains). Explicit merging without links was added to allow adding interactions later on between the chains, including elastic bonds between chains. The original idea with elastic bonds was to have them applied to complexes or to chains (molecules). In recent years it has become fashionable to apply elastic bonds to domains or to use different sets of elastic bonds.

At this point, I think we need to be explicit about elastic bonds: let the user specify the groups, allowing `chains`, `parts` or `molecules`, `all`, or specific groups or combinations, maybe through an index file. Merging will then follow if so required, when elastic bonds are to be generated between molecules. An explicit merge should not be necessary for that. Of course, that option will remain available, because the user may want to combine chains into a single itp file for some reason. 

I realize that this will cause a slight deviation from the behavior of the original martinize, but the problem with that is that the behaviour is not clear enough anymore and is not flexible enough to serve the more complex needs of today.
