### ISSUE TITLE
read_ff assigns incorrect atoms for interaction type virtual_sitesn

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#235]
Dear all, 

The parser for the force-field assigns incorrect atoms for the interaction type virtual_sitesn. The problem with virtual_sitesn as far as I can tell is the following:

read_ff assumes that for all GROMACS interactions a list of atoms comes first and is subsequently followed by parameters. This is not the case for this interaction. In this case you have first the atom for construction of the VS followed by an integer number, which defines the way the VS is constructed, followed by the number of atoms. 

I assume this hasn't been called because in the amino-acid definitions the convention with the '--' syntax is used and then probably the output parser fixes the order. Doesn't change the fact that the function isn't doing what it is supposed to do. 

Cheers,
Fabian

**Comment by pckroon** [comment]
HI Fabian,

indeed virtual_sitesn seems a little funny. 
In `vermouth.gmx.itp.write_molecule_itp` the order gets shuffled again to what GMX expects.
```python3
                if name == 'virtual_sitesn':
                    to_join = [atoms[0], parameters] + atoms[1:]
```
My guess, based on the rest of the code is that we change the semantics of the section: first all atoms, then all the parameters. So, instead of e.g. `1 2 4 5 6` (atom 1 constructed by COM of 4 5 and 6), it would be `C1 C4 C5 C6 -- 2` (atomname C1 constructed by COM of C4 C5 and C6). Note that the `--` is needed to specify the end of atoms and the start of parameters, since it's impossible to know how many atoms to expect.

So, to get back to your analysis of the issue: the parser keeps the order as-is, and the writer puts it back to what GMX expects.

We should rename the section to something else to prevent mistakes, besides clear documentation.

**Comment by pckroon** [comment]
Note that this will be resolved after #230 is merged.

**Comment by fgrunewald** [comment]
still is incorrect when using just indices but this can be pointed out in a FF doc or otherwise one can use an itp reader, which will come soon. In fact it might be better to ban files based on indices all together and just have the FF format with atom names

**Comment by fgrunewald** [comment]
So for vermouth FF-reader this will be the default behaviour and otherwise one can use the itp reader. I'll keep this in mind for the Documentation but the issue appears covered.
