### ISSUE TITLE
HIS Tautomers not automatically detected

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/vermouth-martinize#323]
Hi, 

I'm trying to martinzie a protein with the N1-H tautomer of histidine. However, martinize currently says it cannot identify the modification on this aminoacid. I'm a little confused because at least in M3 as I recall the parameters for both versions should be the same (they are in M2). When I look in the mapping files it also says that this would be automatically recognized. But it seems that it is not. Is this a data-file issue? Should the AA be renamed in the PDB? How was this envisioned to work?

**Comment by pckroon** [comment]
Hi,

The modification needs to be present in 3 places in the data files: The source FF (usually universal), the target FF (in this case M3?), and the mapping between the two.

**Comment by fgrunewald** [comment]
Small update, so the modification(s) now get(s) detected and produces the correct result but yields warning because mappings are missing. This is somehow very confusing, as a user I'd say.

**Comment by KasperBuskPedersen** [comment]
Can confirm this warning/error/bug when inputting histidine tautomers is indeed very confusing. As far as I have understood, martini3 also take the hydrogens into account when mapping (center of geometry), and tautomers would therefore slightly change the bead coordinates. However, the difference between HSE and HSD would likely be insignificant. My problem is that martinize2 does not recognize HSP nor assigns the positive charge and donor label correctly and martinize2 -h does not provide any useful info/syntax in this regard.

How i expected it worked: Martinize2 would read either charmm histidine residue names (HSE, HSD, HSP) or amber (HIE,HID,HIP) and map beads + topology accordingly. 

How I got it working: After reading the above i figured that i could just ignore the mapping warnings. First, this left me with a topology where all histidines were missing.  Changing all histidine names to HIS in the input .pdb, i could get them in the CG topology and then manually correct the topology to have HSP (charge+donor label) on the relevant histidines.

It would be very helpful if anyone could provide an example of how to do this the intended way.

Best regards
Kasper

**Comment by pckroon** [comment]
This definitely needs addressing. 

My idea is that there will be a new processor (probably before repair_graph, but at least before mapping) that renames residues such as HSE/HSD/HSP/ASP0/... to the correct residue name (HIS/ASP in this case) and adds the relevant modifications to the residue. That way most data is deduplicated and allow for maximal flexibility. It does require addition of new code, and a way to store the renaming data. 

I won't take out the mapping warnings, since they signify that the user *must* make a choice on whether the distinction between HSE/HSD is important. 

As for renaming all residues, you can do this from the CLI as well: `martinize2 ... -mutate HSD:HIS` without having to modify the input pdb by hand. 
The fact that the martini3 ff does not have the modifications (or their mappings) for HSP/... is an additional complicating factor. I'll see if I can find/recruit someone to add those to `vermouth/data/force_fields/martini3001/modifications.ff`. If you're up for that be sure to let me know ;) You'll have to reverse-engineer the file format from the existing files, unfortunately, but I can provide more details when/if required.

**Comment by KasperBuskPedersen** [comment]
Dear Peter,
Unfortunately I cannot take time out from my ph.d. project right now to have a look at it. Otherwise I would be happy to help :). I am actually visiting in Siewert-Jan's group in September-December, maybe i'll meet you there.  
Best regards Kasper

**Comment by pckroon** [comment]
> I am actually visiting in Siewert-Jan's group in September-December, maybe i'll meet you there.

My contract ends on 1 August, so we'll just miss each other. I'll still be nearby though, so we could schedule a meeting, but let's discuss that over mail instead of here.

**Comment by KasperBuskPedersen** [comment]
Hi again

I just realized that histidine in M3 is asymmetric (i dont think it was the case in the beta version), so the mapping between HSE and HSD actually matters quite alot because of the a/d label assignment. 
Right now "HIS" maps to 

P2   1 HIS BB  1  0.0
TC4  1 HIS SC1 2  0.0
TN6d 1 HIS SC2 3  0.0
TN5a 1 HIS SC3 4  0.0

I feel like this should be the HSD tautomer, but I am not sure. 
@pckroon, do you know whether this is correct? I feel like this should be documented somewhere, but I have been unable to find it.

Then HSE should be(?):

P2   1 HIS BB  1  0.0
TC4  1 HIS SC1 2  0.0
TN6a 1 HIS SC2 3  0.0
TN5d 1 HIS SC3 4  0.0

Also, in the M3 force field file "aminoacids.ff" residue name HIH seems to be HSP - however martinize2 does not recognize HIH as a name in the input pdb. 
By analogy HSP should be:

P2   1 HIS BB  1  0.0
TC4  1 HIS SC1 2  0.0
TN6d 1 HIS SC2 3  0.0
TQ2d 1 HIS SC3 4  1.0

Best regards
Kasper

**Comment by pckroon** [comment]
I'm the wrong person to ask about model parameters unfortunately. Maybe @paulocts has any input on this.
As for actually including these in the repo I'm the answer is going to be "tough cookie". AFAIK the current policy is to wait for the M3protein paper, which is in the works... I'll try to keep you posted

**Comment by paulocts** [comment]
Hi guys

For me, the the bead assignments for HSE and HSD are good enough...I would adapt the bonded lengths a bit. But, in case you keep the same, it should not be so bad. 

We still did not extensively tested HSP. A conservative solution is the one proposed here, which is kind of inspired in Martini 2, right?   However, in my view, the best model would be something like:

P2 1 HIS BB 1 0.0
TC4 1 HIS SC1 2 0.0
TN6dq 1 HIS SC2 3 0.5
TN6dq 1 HIS SC3 4 0.5

The labels "q" were designed exactly for large charged molecules, which the best representation would be partial charges delocalized in different beads. This was extensively tested for ionic liquids but not for this particular imidazolium ring. I think this would be the best model but we need more tests to be sure. One potential issue here is that this maybe this is not the best distribution of partial charges. Ideally, the values of the bead partial charges should be computed,
redistributing the atomic partial charges and dipoles over the bead centers. Maybe, some partial charge also could be placed in TC4 bead ... Bead chemical types could slightly change as well. Please read more details in page 14 of the SI material of Martini 3 paper. 

These tautomers of imidazolium should be part of the future Martini 3 Protein paper. Let's hope we finish soon!

Good luck, Kasper.

**Comment by fgrunewald** [comment]
they are now provided that the appropriate residue name is given. Complete automatic detection may be implemented in the future.
