### ISSUE TITLE
Incorrect residue numbering when merging chains

### ISSUE THREAD

**Issue by bisejdiu** [marrink-lab/vermouth-martinize#366]
## Issue
When merging chains that have discontinuities in their residue numbering, the output CG file will have incorrect residue numbers. 

## Reproduce
An example file can be downloaded from here: https://gpcrdb.org/structure/homology_models/cxcr1_human_active
Download the model **without loops**, since it will have several breaks/jumps in how residues are numbered. Running: 

```sh
# if we don't specify-merge R then martinize will generate 7 topology files. 
martinize2 -f ClassA_cxcr1_human_Active_6LFO_2021-04-08_GPCRdb_WL.pdb -x cg.pdb -o topol.top -ff martini3001 -scfix -cys auto -dssp -merge R
```

the output `cg.pdb` will have wrong/mismatching residue numbers. E.g., residue SER - 72 in the input pdb has been renumbered to residue SER - 139, residue GLY-106 has been renumbered to GLY - 274, and so on, with the final residue numbers being 1310 in the CG structure instead of 323. 

## Cause of Error 
I am not very familiar with the code, but it seems to me that martinize adds the start number of the new chain to the last residue number of the preceding chain. That's because:
67 + 72 = 139
67 + 101 + 106 = 274
... 
67 and 101 being the last residue numbers of the preceding "chain".  

## Solution
A good solution, at least as a quick fix, would be to have the option to keep residue numbers from the input file, or perhaps have this be the default option when `-merge` has only one argument (i.e. if we only loop once here: https://github.com/marrink-lab/vermouth-martinize/blob/master/bin/martinize2#L710) 
If we don't specify `-merge` at all, then martinize2 will generate 7 itp files (which, at least for this case, is really not ideal), even though all residues belong to the same chain.

**Comment by pckroon** [comment]
Thanks for the detailed report (again!). I'm afraid this one will take a bit longer to resolve than the last one.
Merging chains is done by `vermouth.processors.merge_chains.merge_chains`. This function will call `vermouth.molecule.Molecule.merge_molecule` with the appropriate connected components (i.e. the subchains).

`Molecule.merge_molecule` calculates the residue number offset by taking the residue number of the node with the largest index. I think this explains the behaviour you see.

I would suggest the following solution in `Molecule.merge_molecule`:
1) Find the highest currently used residue number (rather than taking it from the last node)
2) for every residue in the molecule to be added\*, if the residue number is larger than the current max residue number, use it as is. Else, use current max residue number + 1. Update current max residue number.
3) `merge_chains` should sort the molecules/chains to cause the fewest possible renumberings. Or by chain ID?

I think this would work for the following use cases: 
- multiple chains (A and B), which are both numbered starting at 1 (result: consecutive numbers);
- A and B with non-overlapping numbering (result: original numbers);
- A and B with partial overlapping numbering (result: consecutive numbers); 
- one disconnected chain (result: original numbers)

Do you think this would work? Am I missing a use case?
\* Sort residues by residue number first! This is also a bit of work, since merge_molecule works per atom at the moment.

**Comment by bisejdiu** [comment]
The solution that I came up with is a bit simpler, which seems to work for my use case, but is not generalizable compared to your suggestion. 

What I did was to add a keyword argument here: https://github.com/marrink-lab/vermouth-martinize/blob/1b7826784ab68bcf921cf91c180c2332957dfc6f/vermouth/processors/merge_chains.py#L57

like this: 
```python
merged.merge_molecule(molecule, offset_bool=True)
```

and then made the following changes to `Molecule.merge_molecule`: 

```python
# accept the new argument
def merge_molecule(self, molecule, offset_bool=False):
  ...
  ...
  if self.nodes():
    ...
    ... 
    # no offset when merging 
    if offset_bool:
        residue_offset = 0
```

This seems to work for the test file above. It also very likely breaks all other uses of  `-merge` because I am hardcoding the behaviour, but that's fine. I did a few comparisons of the files generated, and the changes above seem to only affect the residue numbering and nothing else, which is good. There also does not seem to be any effect on `offset_charge_group` variable values.

**Comment by fgrunewald** [comment]
@pckroon why do we even relabel the resids in the first place? That only considers the use-case, where the two molecules are entirely separate molecules or not? If they would be two separated chains with different identifier they could have the same resid right?

**Comment by pckroon** [comment]
I guess it boils to down to formalizing what we use to define residues as different. We need to be able to that to keep them identifiable for users, but so far it's one or multiple of: resid, resname, chain, molecule id (chains separated by TER but with the same chain id), chemical structure, and possibly there are other options still. We /really/ need to pick a definition (that's intuitive to end users) and stick to it.

**Comment by fgrunewald** [comment]
this has been solved. Setting the '-resid input' flag will keep the resids provided in the input pdb file
