### ISSUE TITLE
Adding Modifications

### ISSUE THREAD

**Issue by Entropy134** [marrink-lab/vermouth-martinize#380]
Hello,
The peptides that I have simulated have an amidated C-terminus (CT2 in Charmm27) so I would like to use a modification to account for this. Can you please help me find what and where I should add information to accomodate this?

I have modifying data>force_fields>universal>modification.ff to include

[ modification ]
CT2-ter
[ atoms ]
CA {"element": "C"}
C {"element": "C"}
O {"element": "O"}
NT {"element": "N", "PTM_atom": true}
HT1 {"element": "H", "PTM_atom": true}
HT2 {"element": "H", "PTM_atom": true}
[ edges ]
CA C
C O
C NT
NT HT1 
NT HT2 

But I am still receiving the following error,
NameError: CT2-ter is not known as a modification for force field charmm27.ff

Thank you for your help resolving this matter,
Luke

**Comment by pckroon** [comment]
Hello hello,

Your modification looks good! (Note: the modification does not contain MD parameters such as charge, atomtype, etc. This is fine though) The only issue I can see is that you defined it for the force field 'universal' (which is also good). However, the error mentions charmm27. What's your command line invocation? What force field do you want to use for your simulation?

Peter

**Comment by pckroon** [comment]
Hello! Sorry for the slow reply, busy week.

Looking at your command line, I spot the following: your input system is (should be) named according to charmm27 conventions (`-from`), and you want to simulate your system using the universal force field (`-ff`). This is fishy, since the universal FF does not contain actual MD parameters such as non-bonded types and force constants. 

I suggest you use `-from universal` (which is the default), since the universal ff atom names are based on charmm36, so enough atom names should match. Then use `-ff martini3001` to create martini3 output.

Note that when adding blocks and modifications you need to add them in 3 places: 1) the input force field (usually universal); 2) the output force field (e.g. martini3001), and 3) the mapping between them.

**Comment by Entropy134** [comment]
Thank you for explaining how to properly use the input flags! I will try your suggestions.

**Comment by Tsjerk** [comment]
@pckroon Is this still an issue? It seems not.
