### ISSUE TITLE
Applying nter and cter flag for protein with different termini ends

### ISSUE THREAD

**Issue by mbrosz** [marrink-lab/vermouth-martinize#419]
Hi Martinize2-Developer Team, 

I currently try to martinize2 a protein with multiple chains and different types of termini. 
For example, one chain is capped with an ACE and NME residue. Another chain is capped with a GLY and ALA residue. So if I know use the default c-ter and n-ter flag, the ACE, NME cap is not recognized. On the other hand, if I use -nter ACE -cter NME the GLY, ALA termini are not recognized.
 
I was wondering if there is the possibility to provide a list for the n-ter flag to allow multiple termini to be recognized? Something like -nter [ACE, N-ter] ? Or may be there is a more clever solution to this issue, which is already implemented somehow, and I just can not see it. 

Another issue, I encountered is that if one martinzes a protein ranging from -1100 to 1100 nm in one dimension. The PDB-Write function overwrites the "-" sign for values smaller -1000. As a result, part of the molecule is shifted to the positive direction. 
For example, an atom in the AA pdb at position x=-1050 would be placed at position +1050 in the CG pdb.  

May be this issue is already solved, however my current solution was to change the output format of the coordinate from 8.3 to 8.2. The coordinates look like -1050.32 instead of 1050.323. This solution is not nice, since it also cuts off the coordinates for values larger -1000. For example,  -989.82 instead of -989.824, although there is space for one more digit.  

Thanks for your advice and best,
Matthias

**Comment by pckroon** [comment]
Hello hello!

You can (should be able to) assign different termini to different chains with the `-modify` flag. But, see also #295 --- we can detect modifications based on the atoms in the pdb file, but this gets clobbered for the termini.

For the PDB writer truncating the sign: this is a bit tricky. We currently use `8.3ft` as format string: 8 characters with 3 decimals. Maybe that should be changed to ` 8.3ft` (space significant) so that a character will be reserved for the sign. There's an annoying interaction with https://github.com/marrink-lab/vermouth-martinize/blob/master/vermouth/truncating_formatter.py though, since that will always truncates from the front. PR welcome ;)

**Comment by mbrosz** [comment]
Hi, 
thanks for the fast reply concerning my issue with Martinize2. I kind of found a solution to both issues:

**Comment by fgrunewald** [comment]
@mbrosz has this been resolved or is it still open?

**Comment by mbrosz** [comment]
Ah sorry, yes for sure the issue has been resolved. Thanks again for asking.
