### ISSUE TITLE
Neither martinize2 nor vermouth have a version number

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#66]
And this does not look very serious coming from us...

Should martinize2 be versioned separately from vermouth? What version number should we start with? How do we keep martinize2 and vermouth versions in sync?

Also, in the current version of martinize, there is a version number that is never updated but that ranges from 2.4 to 2.6 depending on where you download the file. Should we rename martinize2 to martinize3 and start counting with martinize 3.0 to avoid confusion? It will also fit nicely with martini getting its version 3.

**Comment by Tsjerk** [comment]
I would say that the new martinize is an integral part of Vermouth and gets versioned with that. The command to execute should just be 'martinize'. To make sure to avoid any confusion, we could have versioning based on the year. That seems proper for Vermouth anyway. The statement to include in the materials and methods section should than be 'the preparation of the coarse grain system was done using a Vermouth from 2018 - version ... to be precise'.

**Comment by jbarnoud** [comment]
Martinize is part of vermouth for now, but as time go it will make less sense to have them so tightly coupled. Having them tightly coupled means that somebody using cartographer will have to update cartographer when martinize gets an update, even if that update does not affect vermouth and therefore not cartographer.

Version numbering by year is fine by me. But it breaks the semantics of a version number. What if we release a version mid-year that breaks some backward compatibility? How do we bump the version number?

I fully agree that mertinize2 should be renamed just martinize at some point.

**Comment by pckroon** [comment]
I'm not in favor of using the year as versioning scheme. To me SemVer makes more sense: it clearly shows when something is an interface breaking change.

From a versioning point of view separating martinize from vermouth is a good idea --- but like @jbarnoud said this will confuse users to no end. And it would mean users will need to report 2 version numbers: both martinize and vermouth.

A third option might be to drop the name martinize in favor of vermouth and start at version 1.0.0 upon release. This we keep the tight coupling between martinize2 and vermouth since 90% of the use cases will be resolution transformations. Internally the CLI and API of vermouth will still be nicely separated of course.

And yes, the onus for staying up to date with your dependencies lies downstream. We just need to be careful not to completely break the API too often.

**Comment by jbarnoud** [comment]
On a marketing point of view, I think we should keep the martinize name. It is a well established name for exactly that tool. It is what people is expecting to find. Dropping the name is the easiest solution, though.

**Comment by Tsjerk** [comment]
martinize is to be nothing more than a (marketing) name for a thin shell of auxiliary interface to vermouth... 
hmm, that means that the version of martinize will automatically be vermouth/x.y.z and as such that problem is solved. No more separate version for martinize, and for sure no more separate life. It's just like a male lantern fish that found a spouse...

**Comment by jbarnoud** [comment]
This works for me. `martinize --version` with output something in the line of `martinize with vermouth x.y.z`.

What is the current version? 0.1.0-dev0?

**Comment by jbarnoud** [comment]
I looked at ways to automate the update of the version number. If the idea is to have a version number per commit, then the options I can think of are:

* local git hook: we all install a git hook on our computer that update the version number at each commit. It is going to break when we rewrite the history (which I do every day these days), and when external contributor will be a thing
* travis CI job: we can repurpose a travis CI build to make a commit. Unless we make travis rewrite the history on master (and I bite everybody who suggest it is a good idea), the versioning would be on a PR basis rather than commit basis. There are reliability issues to consider.
* webhook: we write a small webapp that speaks with github API and we host it on the martini webserver; maybe we can slay that dragon

**Comment by pckroon** [comment]
https://docs.openstack.org/pbr/latest/user/features.html#version seems to do what I had in mind. @jbarnoud your options look rather fragile to be honest.

**Comment by jbarnoud** [comment]
I am glad the fragility of the options transpired from my message. I read your link, I am not sure I understand if it works without git, *e.g.* from a tarball, or similarly from pip/conda.

**Comment by pckroon** [comment]
Hmmn. I'm also not sure. I'd say it's worth a try. I also think https://github.com/tBuLi/symfit uses this, so we could take a peak.
It might be it adds pbr as an install requirement, but I haven't read the docs attentively enough.

**Comment by jbarnoud** [comment]
It seems to be the solution indeed, but I fail to find how to set `__version__` in the lib. There seem to be a way with `pbr.version`, but it requires pbr to be a regular requirement and not only a setup requirement, which does not seem to match the examples in the doc.

**Comment by pckroon** [comment]
I would be ok with getting PBR as a runtime requirement if it solves our version issues.

**Comment by jbarnoud** [comment]
The problem is not so much to have pbr at runtime. The problem is that the documentation I found does not fulfil my expectations. If you find any that actually explains the correct way to access the version number from the library, then PBR it is.

**Comment by pckroon** [comment]
https://docs.openstack.org/pbr/latest/reference/api/pbr.html#pbr.version.VersionInfo ?
