### ISSUE TITLE
RepairGraph creates unwanted atoms

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/vermouth-martinize#77]
In some cases, the `RepairGraph` processor duplicate some atoms. The issue is demonstrated [in a gist](https://gist.github.com/jbarnoud/20f20ee4b3e2d6afe92b6d5925a7f52c#file-issue-repairgraph-ipynb). It is also visible in the branch from PR #2 : <https://gist.github.com/jbarnoud/20f20ee4b3e2d6afe92b6d5925a7f52c#file-issue-repairgraph-pr2-ipynb>.

**Comment by pckroon** [comment]
Hmmn, it shouldn't be doing that.

Does molecule have edges?
What I can think of is that every other atom get's recognized by the MCS algorithm, and the rest gets duplicated.

**Comment by jbarnoud** [comment]
I added the edges, and indeed it is better. But there is still a duplication: <https://gist.github.com/jbarnoud/6cdca889ef040d5836f705127d5087c7>

It is different here: there is no additional atom, but there are two that share the same name. It is of notice that the atom that got renamed with an already existing name is a N-terminal hydrogen that is not in the block. The issue is then that a "PTM" can be renamed incorrectly when not recognized. The good point is that in #2, it gets recognized as a PTM, even though it is wrongly renamed.

**Comment by pckroon** [comment]
Ok, that makes more sense. Atoms with degree 1 (e.g. hydrogens) are treated specially in the isomorphism, otherwise you might end up with a combinatoric explosion of possible isomorphisms you need to consider (such as an alkane chain). Up until now I decided all hydrogrens are identical, but this might not be the case. Can you think of a case where this will actually go *wrong* though? PTMs are indifferent of atomnames as well, so all that would happen is that the coordinates get exchanged.

**Comment by jbarnoud** [comment]
Would be a sane thing to do indeed.

**Comment by jbarnoud** [comment]
Here is the working notebook thanks to the last commit: https://gist.github.com/jbarnoud/0a0ed4c16b52511e2c99579fe6ed499c
